name : TEST cicd

on: #TRIGGERS
  push:
    branches: [ master ]

  jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2

          - uses: actions/setup-java@v3
            with:
              java-version: 11

         - name : install gradle
  #         run : sudo apt install gradle
           run : gradle/gradle-build-action@v2


         - name: grant permission
           run: chmod +x gradlew

          - name: build android
            run: ./gradlew assembleDebug

          - name: upload to github
              uses: actions/upload-artifact@v3
              with:
                  name: app-debug
                  path: app/build/outputs/apk/debug/app-debug.apk